Repository jefferson-vieira/my-money-app-backend, pull requests merged in 2019-04, with the labels that each got.

#2 heroku prod fix
  src/main/resources/application-prod.yml
Labels: bug

#3 Feature/sgf 6
  .gitignore
  logs/.gitkeep
  src/main/java/com/mymoneyapp/backend/controller/BankingAccountController.java
  src/main/java/com/mymoneyapp/backend/domain/BankingAccount.java
  src/main/java/com/mymoneyapp/backend/mapper/BankingAccountMapper.java
  src/main/java/com/mymoneyapp/backend/mapper/UserMapper.java
  src/main/java/com/mymoneyapp/backend/repository/BankingAccountRepository.java
  src/main/java/com/mymoneyapp/backend/request/BankingAccountRequest.java
  src/main/java/com/mymoneyapp/backend/response/BankingAccountResponse.java
  src/main/java/com/mymoneyapp/backend/service/BankingAccountService.java
  src/main/java/com/mymoneyapp/backend/specification/BankingAccountSpecification.java
Labels: enhancement

#4 SGF-6
  src/main/java/com/mymoneyapp/backend/controller/BankingAccountController.java
  src/main/java/com/mymoneyapp/backend/domain/BankingAccount.java
  src/main/java/com/mymoneyapp/backend/service/BankingAccountService.java
Labels: wontfix
